/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

mod ffi {
    #[cfg(not(target_arch="wasm32"))]
    ispc::ispc_module!(bc7e);
}

#[cfg(not(target_arch="wasm32"))]
pub use ffi::bc7e::*;

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_init(

)
{
    bc7e_compress_block_init(

    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_basic(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_basic(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_fast(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_fast(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_slow(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_slow(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_slowest(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_slowest(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_ultrafast(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_ultrafast(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_veryfast(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_veryfast(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_block_params_init_veryslow(
    p: *mut bc7e_compress_block_params,
    perceptual: bool
)
{
    bc7e_compress_block_params_init_veryslow(
        p,
        perceptual
    )
}

#[no_mangle]
#[cfg(not(target_arch="wasm32"))]
pub unsafe extern "C" fn csbindgen_bc7e_compress_blocks(
    num_blocks: u32,
    pBlocks: *mut u64,
    pPixelsRGBA: *const u32,
    pComp_params: *const bc7e_compress_block_params
)
{
    bc7e_compress_blocks(
        num_blocks,
        pBlocks,
        pPixelsRGBA,
        pComp_params
    )
}

    