/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::ozz_cpp::*;


#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_AnimationBuilder_Build(
    this: *const ozz_animation_offline_AnimationBuilder,
    _input: *const ozz_animation_offline_RawAnimation
) -> u8
{
    ozz_animation_offline_AnimationBuilder_Build(
        this,
        _input
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_AnimationOptimizer_AnimationOptimizer(
    this: *mut ozz_animation_offline_AnimationOptimizer
)
{
    ozz_animation_offline_AnimationOptimizer_AnimationOptimizer(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_AdditiveAnimationBuilder_AdditiveAnimationBuilder(
    this: *mut ozz_animation_offline_AdditiveAnimationBuilder
)
{
    ozz_animation_offline_AdditiveAnimationBuilder_AdditiveAnimationBuilder(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawAnimation_JointTrack_Validate(
    this: *const ozz_animation_offline_RawAnimation_JointTrack,
    _duration: f32
) -> bool
{
    ozz_animation_offline_RawAnimation_JointTrack_Validate(
        this,
        _duration
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawAnimation_Validate(
    this: *const ozz_animation_offline_RawAnimation
) -> bool
{
    ozz_animation_offline_RawAnimation_Validate(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawAnimation_size(
    this: *const ozz_animation_offline_RawAnimation
) -> usize
{
    ozz_animation_offline_RawAnimation_size(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawAnimation_RawAnimation(
    this: *mut ozz_animation_offline_RawAnimation
)
{
    ozz_animation_offline_RawAnimation_RawAnimation(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_FixedRateSamplingTime_FixedRateSamplingTime(
    this: *mut ozz_animation_offline_FixedRateSamplingTime,
    _duration: f32,
    _frequency: f32
)
{
    ozz_animation_offline_FixedRateSamplingTime_FixedRateSamplingTime(
        this,
        _duration,
        _frequency
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawSkeleton_Validate(
    this: *const ozz_animation_offline_RawSkeleton
) -> bool
{
    ozz_animation_offline_RawSkeleton_Validate(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawSkeleton_num_joints(
    this: *const ozz_animation_offline_RawSkeleton
) -> c_int
{
    ozz_animation_offline_RawSkeleton_num_joints(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawSkeleton_RawSkeleton(
    this: *mut ozz_animation_offline_RawSkeleton
)
{
    ozz_animation_offline_RawSkeleton_RawSkeleton(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_RawSkeleton_RawSkeleton_destructor(
    this: *mut ozz_animation_offline_RawSkeleton
)
{
    ozz_animation_offline_RawSkeleton_RawSkeleton_destructor(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_ozz_animation_offline_TrackOptimizer_TrackOptimizer(
    this: *mut ozz_animation_offline_TrackOptimizer
)
{
    ozz_animation_offline_TrackOptimizer_TrackOptimizer(
        this
    )
}

    