/* automatically generated by csbindgen */

#[allow(unused)]
use ::std::os::raw::*;

use super::pitchtracker::*;


#[no_mangle]
pub unsafe extern "C" fn csbindgen_Tone_Tone(
    this: *mut Tone
)
{
    Tone_Tone(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_process(
    this: *mut Analyzer
)
{
    Analyzer_process(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_output(
    this: *mut Analyzer,
    begin: *mut f32,
    end: *mut f32,
    rate: f64
) -> bool
{
    Analyzer_output(
        this,
        begin,
        end,
        rate
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_Analyzer(
    this: *mut Analyzer,
    rate: f64,
    id: u32,
    step: c_uint
)
{
    Analyzer_Analyzer(
        this,
        rate,
        id,
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_GetNote(
    this: *mut PtAKF,
    maxVolume: *mut f32,
    weights: *mut f32
) -> c_int
{
    PtAKF_GetNote(
        this,
        maxVolume,
        weights
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_SetVolumeThreshold(
    this: *mut PtAKF,
    threshold: f32
)
{
    PtAKF_SetVolumeThreshold(
        this,
        threshold
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_PtAKF(
    this: *mut PtAKF,
    step: c_uint
)
{
    PtAKF_PtAKF(
        this,
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_PtAKF_destructor(
    this: *mut PtAKF
)
{
    PtAKF_PtAKF_destructor(
        this
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_FindNote(
    this: *mut PtDyWa,
    maxVolume: *mut f32
) -> f64
{
    PtDyWa_FindNote(
        this,
        maxVolume
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_SetVolumeThreshold(
    this: *mut PtDyWa,
    threshold: f32
)
{
    PtDyWa_SetVolumeThreshold(
        this,
        threshold
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_PtDyWa(
    this: *mut PtDyWa,
    step: c_uint
)
{
    PtDyWa_PtDyWa(
        this,
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_Create(
    step: c_uint
) -> *mut Analyzer
{
    Analyzer_Create(
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_Free(
    analyzer: *mut Analyzer
)
{
    Analyzer_Free(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_InputFloat(
    analyzer: *mut Analyzer,
    data: *mut f32,
    sampleCt: c_int
)
{
    Analyzer_InputFloat(
        analyzer,
        data,
        sampleCt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_InputShort(
    analyzer: *mut Analyzer,
    data: *mut c_short,
    sampleCt: c_int
)
{
    Analyzer_InputShort(
        analyzer,
        data,
        sampleCt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_InputByte(
    analyzer: *mut Analyzer,
    data: *mut c_char,
    sampleCt: c_int
)
{
    Analyzer_InputByte(
        analyzer,
        data,
        sampleCt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_Process(
    analyzer: *mut Analyzer
)
{
    Analyzer_Process(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_GetPeak(
    analyzer: *mut Analyzer
) -> f32
{
    Analyzer_GetPeak(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_FindNote(
    analyzer: *mut Analyzer,
    minFreq: f64,
    maxFreq: f64
) -> f64
{
    Analyzer_FindNote(
        analyzer,
        minFreq,
        maxFreq
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_Analyzer_OutputFloat(
    analyzer: *mut Analyzer,
    data: *mut f32,
    sampleCt: c_int,
    rate: f32
) -> bool
{
    Analyzer_OutputFloat(
        analyzer,
        data,
        sampleCt,
        rate
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_Create(
    step: c_uint
) -> *mut PtAKF
{
    PtAKF_Create(
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_Free(
    analyzer: *mut PtAKF
)
{
    PtAKF_Free(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_GetNumHalfTones(

) -> c_int
{
    PtAKF_GetNumHalfTones(

    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_SetVolumeThreshold1(
    analyzer: *mut PtAKF,
    threshold: f32
)
{
    PtAKF_SetVolumeThreshold1(
        analyzer,
        threshold
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_GetVolumeThreshold(
    analyzer: *mut PtAKF
) -> f32
{
    PtAKF_GetVolumeThreshold(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_InputByte(
    analyzer: *mut PtAKF,
    data: *mut c_char,
    sampleCt: c_int
)
{
    PtAKF_InputByte(
        analyzer,
        data,
        sampleCt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtAKF_GetNote1(
    analyzer: *mut PtAKF,
    maxVolume: *mut f32,
    weights: *mut f32
) -> c_int
{
    PtAKF_GetNote1(
        analyzer,
        maxVolume,
        weights
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_Create(
    step: c_uint
) -> *mut PtDyWa
{
    PtDyWa_Create(
        step
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_Free(
    analyzer: *mut PtDyWa
)
{
    PtDyWa_Free(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_SetVolumeTreshold(
    analyzer: *mut PtDyWa,
    threshold: f32
)
{
    PtDyWa_SetVolumeTreshold(
        analyzer,
        threshold
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_GetVolumeThreshold(
    analyzer: *mut PtDyWa
) -> f32
{
    PtDyWa_GetVolumeThreshold(
        analyzer
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_InputByte(
    analyzer: *mut PtDyWa,
    data: *mut c_char,
    sampleCt: c_int
)
{
    PtDyWa_InputByte(
        analyzer,
        data,
        sampleCt
    )
}

#[no_mangle]
pub unsafe extern "C" fn csbindgen_PtDyWa_FindNote1(
    analyzer: *mut PtDyWa,
    maxVolume: *mut f32
) -> f64
{
    PtDyWa_FindNote1(
        analyzer,
        maxVolume
    )
}

    